---
title: Greentwip
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    comments: true
    share: true
- scope:
    path: _recipes
    type: recipes
  values:
    layout: post
    comments: true
    share: true
remote_theme: mmistakes/so-simple-theme
locale: en-US
description: Technology and Videogames
baseurl: ''
url: https://greentwip.xyz
logo: "/images/greentwiphq.jpg"
title_image: https://greentwip.xyz/images/greentwiphq.jpg
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 
mathjax:
  enable: true
  combo: tex-svg
  tags: ams
google_fonts:
- name: Source Sans Pro
  weights: 400,400i,700,700i
- name: Lora
  weights: 400,400i,700,700i
twitter:
  username: greentwip
liquid:
  error_mode: strict
permalink: "/:categories/:title/"
markdown: kramdown
feed:
  path: atom.xml
paginate: 10
paginate_path: "/page:num/"
search_full_content: false
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
- jekyll-redirect-from
author:
  name: Greentwip
  picture: "/images/greentwiphq.jpg"
  email: development@greentwip.xyz
  twitter: greentwiphq
  links:
  - title: Twitter
    url: https://twitter.com/greentwiphq
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/greentwip
    icon: fab fa-github-square
footer_links:
- title: Twitter
  url: https://twitter.com/greentwiphq
  icon: fab fa-twitter-square
- title: GitHub
  url: https://github.com/greentwip
  icon: fab fa-github-square
- title: Feed
  url: atom.xml
  icon: fas fa-rss-square
