---
title: Greentwip
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  programming:
    title: Programming
    output: true
  uploads:
    title: Uploads
    output: true
description: Technology and Video Games.
baseurl: 
url: https://greentwip.xyz
remote_theme: "mmistakes/so-simple-theme@3.2.0"